export type Styles = {
  'flex-item--align-auto': string;
  'flex-item--align-baseline': string;
  'flex-item--align-center': string;
  'flex-item--align-flex-end': string;
  'flex-item--align-flex-start': string;
  'flex-item--align-stretch': string;
  'flex-item--basis-0': string;
  'flex-item--basis-10': string;
  'flex-item--basis-100': string;
  'flex-item--basis-15': string;
  'flex-item--basis-20': string;
  'flex-item--basis-25': string;
  'flex-item--basis-30': string;
  'flex-item--basis-35': string;
  'flex-item--basis-40': string;
  'flex-item--basis-45': string;
  'flex-item--basis-5': string;
  'flex-item--basis-50': string;
  'flex-item--basis-55': string;
  'flex-item--basis-60': string;
  'flex-item--basis-65': string;
  'flex-item--basis-70': string;
  'flex-item--basis-75': string;
  'flex-item--basis-80': string;
  'flex-item--basis-85': string;
  'flex-item--basis-90': string;
  'flex-item--basis-95': string;
  'flex-item--basis-auto': string;
  'flex-item--grow-0': string;
  'flex-item--grow-1': string;
  'flex-item--grow-2': string;
  'flex-item--grow-3': string;
  'flex-item--grow-4': string;
  'flex-item--grow-5': string;
  'flex-item--grow-6': string;
  'flex-item--grow-7': string;
  'flex-item--grow-8': string;
  'flex-item--grow-9': string;
  'flex-item--order-0': string;
  'flex-item--order-1': string;
  'flex-item--order-2': string;
  'flex-item--order-3': string;
  'flex-item--order-4': string;
  'flex-item--order-5': string;
  'flex-item--order-6': string;
  'flex-item--order-7': string;
  'flex-item--order-8': string;
  'flex-item--order-9': string;
  'flex-item--shrink-0': string;
  'flex-item--shrink-1': string;
  'flex-item--shrink-2': string;
  'flex-item--shrink-3': string;
  'flex-item--shrink-4': string;
  'flex-item--shrink-5': string;
  'flex-item--shrink-6': string;
  'flex-item--shrink-7': string;
  'flex-item--shrink-8': string;
  'flex-item--shrink-9': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
